### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by Miao-WangHao** [jqin4749/MindVideo#1]
大佬，代码什么时候开源啊，想体验一下。

**Comment by jqin4749** [comment]
非常感谢对我们的项目感兴趣！目前我们的文章和代码正在同行评审当中，当完成相关评审流程我们会第一时间开源代码。谢谢！
Thanks for your interest in our project! Our preprint and codes are being peer-reviewed right now. We will open-source the code as soon as the review process ends.
